################################################################
###                    *** WARNING ***
################################################################
###
### Use a proper text editor when editing this file.
### Do not use tab characters in this file, use spaces.
###
### Keep at least one space after a colon, like so:
###
###   key: value
###
###
### Never edit or add a value to lines that have no default value, like:
###
###   micronaut:
###
###
### Just leave them be. A default value may be an empty string like so: ""
###
###
### You can wrap most values into quotation marks, except numbers and booleans:
###
###   someUrl: "http://example.com"
###   someToken: "123.qwe.456[DFG="
###   somePortNumber: 22
###   useSomeFeature: true
###
###
### You can have a list of things like this:
###
###   listOfStrings: ["string1", "string2", "string3"]
###
### or like this:
###
###   listOfStrings:
###     - "string1"
###     - "string2"
###     - "string3"
###
###
### More information on correctly formatting yaml files: http://www.yaml.org/start.html

################################################################
###                 Basic configuration
################################################################

micronaut:
  application:
    name: Docker-Agent

  server:
    host: localhost                       # Hostname of the Agent. This will probably not be localhost in any production environment
    port: 8885                            # Server Port Change this if the Port is already in use


  ################################################################
  ###                 Security configuration
  ################################################################

  security:
    enabled: true                         # Set this to false to turn off security completely (NOT RECOMMENDED)
    reject-not-found: false               # Set to true to return a 401 instead of 404 on pages not found
    authentication: idtoken               # Authentication type, used by keycloak. Should not be changed

    basic-auth:
      enabled: true                       # Set to false to disable the builtin admin:admin development account.

    oauth2:
      enabled: false                      # Set to true to enable oauth2 / keycloak authentication.
      clients:
        keycloak:
          client-id: docker-agent         # Client id of the client generated in keycloak
          client-secret: <client-secret>  # Put your generated client secret here if you are using access_type = confidential
          openid:
            issuer: <http://issuer/url>   # Url to the Issuer, includes the Realm

    intercept-url-map:
      - pattern: /**
        access:
          - isAuthenticated()


  ################################################################
  ###                 Routing configuration
  ################################################################

  router:
    versioning:
      enabled: true                       # Set this to false to disable the legacy V0 API Endpoints.
      default-version: 1
      header:
        enabled: true
        names:
          - X-API-VERSION
          - Accept-Version


################################################################
###                 Agent configuration
################################################################

agent:

  # Override the Url to connect to the Docker Engine
  # This can be in one of 3 formats
  #
  # 1. Unix Socket:     unix:///var/run/docker.sock
  # 2. Windows npipe:   npipe:////./pipe/docker_engine
  # 3. TCP connect      tcp://Hostname:Port
  #
  # Note: The System will attempt to set the url depending on your os if not manually specified
  #
  # TCP does currently not support TLS authenticated against the Docker Engine
  # and would require to open an unsecured tcp port on your machine.
  url: unix:///var/run/docker.sock

  # Attempt to connect to the specified docker url above on startup.
  # If disabled you will manually call the /docker/connect endpoint to initiate the connection
  auto-connect: true

  ssl:

    # type of SSL configuration. Can be 'none', 'keystore' or 'pem_files'
    # Setting this to none disables SSL configuration
    type: none

    keystore-file:                        # Path to either a .jks or .pkcs12 file.
    keystore-pass:                        # Password for the keystore or pkcs12 file.

    # Path to a directory containing a ca.pem, key.pem & cert.pem
    # These files must be named and have the file extension as described above!
    pem-directory:

  orchestrator:
    enabled: false

    # Base Url of the Orchestrator, The orchestrator needs to live somewhere from where it can reach the agent
    url: http://localhost:8080

    # Set to the value of micronaut.security.register-token from your orchestrator configuration
    # !If token is not being used remove or leave commented out!
    token: my-super-secure-registration-password
